"""initial schema

Revision ID: 433c854dbf40
Revises:
Create Date: 2026-09-28 06:02:48.526254

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "433c854dbf40"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "role",
            sa.Enum("artist", "regular", name="user_role"),
            server_default="regular",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "artist_follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "follower_id <> artist_id", name=op.f("ck_artist_follows_no_self_follow")
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["users.id"],
            name=op.f("fk_artist_follows_artist_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_artist_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "artist_id", name=op.f("pk_artist_follows")),
    )
    op.create_index(
        op.f("ix_artist_follows_artist_id"), "artist_follows", ["artist_id"], unique=False
    )
    op.create_table(
        "galleries",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cover_image_url", sa.String(length=2048), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_galleries_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_galleries")),
    )
    op.create_index(op.f("ix_galleries_owner_id"), "galleries", ["owner_id"], unique=False)
    op.create_table(
        "artworks",
        sa.Column("gallery_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_for_sale", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT is_for_sale OR price_cents IS NOT NULL",
            name=op.f("ck_artworks_for_sale_requires_price"),
        ),
        sa.CheckConstraint(
            "price_cents IS NULL OR price_cents > 0", name=op.f("ck_artworks_price_positive")
        ),
        sa.ForeignKeyConstraint(
            ["gallery_id"],
            ["galleries.id"],
            name=op.f("fk_artworks_gallery_id_galleries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artworks")),
    )
    op.create_index(op.f("ix_artworks_gallery_id"), "artworks", ["gallery_id"], unique=False)
    op.create_table(
        "gallery_follows",
        sa.Column("follower_id", sa.Uuid(), nullable=False),
        sa.Column("gallery_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_gallery_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gallery_id"],
            ["galleries.id"],
            name=op.f("fk_gallery_follows_gallery_id_galleries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "gallery_id", name=op.f("pk_gallery_follows")),
    )
    op.create_index(
        op.f("ix_gallery_follows_gallery_id"), "gallery_follows", ["gallery_id"], unique=False
    )
    op.create_table(
        "artwork_images",
        sa.Column("artwork_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position >= 0 AND position < 5", name=op.f("ck_artwork_images_position_range")
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artworks.id"],
            name=op.f("fk_artwork_images_artwork_id_artworks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artwork_images")),
        sa.UniqueConstraint(
            "artwork_id", "position", name=op.f("uq_artwork_images_artwork_id_position")
        ),
    )
    op.create_index(
        "uq_artwork_images_one_primary",
        "artwork_images",
        ["artwork_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "artwork_likes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("artwork_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artworks.id"],
            name=op.f("fk_artwork_likes_artwork_id_artworks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_artwork_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "artwork_id", name=op.f("pk_artwork_likes")),
    )
    op.create_index(
        op.f("ix_artwork_likes_artwork_id"), "artwork_likes", ["artwork_id"], unique=False
    )
    op.create_table(
        "artwork_saves",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("artwork_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artworks.id"],
            name=op.f("fk_artwork_saves_artwork_id_artworks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_artwork_saves_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "artwork_id", name=op.f("pk_artwork_saves")),
    )
    op.create_index(
        op.f("ix_artwork_saves_artwork_id"), "artwork_saves", ["artwork_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("artwork_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artworks.id"],
            name=op.f("fk_comments_artwork_id_artworks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_comments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_artwork_id"), "comments", ["artwork_id"], unique=False)
    op.create_index(op.f("ix_comments_user_id"), "comments", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_user_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_artwork_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_artwork_saves_artwork_id"), table_name="artwork_saves")
    op.drop_table("artwork_saves")
    op.drop_index(op.f("ix_artwork_likes_artwork_id"), table_name="artwork_likes")
    op.drop_table("artwork_likes")
    op.drop_index(
        "uq_artwork_images_one_primary",
        table_name="artwork_images",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_table("artwork_images")
    op.drop_index(op.f("ix_gallery_follows_gallery_id"), table_name="gallery_follows")
    op.drop_table("gallery_follows")
    op.drop_index(op.f("ix_artworks_gallery_id"), table_name="artworks")
    op.drop_table("artworks")
    op.drop_index(op.f("ix_galleries_owner_id"), table_name="galleries")
    op.drop_table("galleries")
    op.drop_index(op.f("ix_artist_follows_artist_id"), table_name="artist_follows")
    op.drop_table("artist_follows")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # Autogenerate does not drop Postgres enum types.
    sa.Enum(name="user_role").drop(op.get_bind(), checkfirst=True)
